
name: "Sonar Build Breaker Github Action"
description: "Check the status of the Sonar Quality Gate result"
inputs:
  sonarqube_url:
    description: "URL of your SonarQube instance"
    required: true
  sonarqube_token:
    description: "SonarQube token for the project"
    required: true
  projectKey:
    description: "The project's unique key. Allowed characters are: letters, numbers, -, _, . and :, with at least one non-digit."
    required: true
    default: ""
  projectName:
    description: "The project's name"
    required: true
  # task_id:
  #   description: "Task id from Properties-file check Quality Gate"
  #   required: true
# runs:
#   using: "composite"
#   steps:
#     - run: ${{ github.action_path }}/break_build.sh ${{ inputs.sonarqube_url }} ${{ inputs.sonarqube_token }} ${{ inputs.task_id }}
#       shell: bash
runs:
  using: "docker"
  image: "Dockerfile"
  # args:
  #   - ${{ inputs.pokemon_id}}