
name: "Sonar Build Breaker Github Action"
description: "Check the status of the Sonar Quality Gate result"
inputs:
  sonarqube_url:
    description: "URL of your SonarQube instance"
    required: true
  sonarqube_token:
    description: "SonarQube token for the project"
    required: true
  projectKey:
    description: "The project's unique key. Allowed characters are: letters, numbers, -, _, . and :, with at least one non-digit."
    required: true
    default: ""
  projectName:
    description: "The project's name"
    required: false
  projectVersion:
    description: "The project's version"
    required: false
  projectBaseDir:
    description: "Set the sonar.projectBaseDir analysis property"
    required: false
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"