# on: push

# jobs:
#   custom_test:
#     runs-on: ubuntu-latest
#     name: Test locally with act
#     steps:
#       - uses: actions/checkout@v1
#       - name: Check Sonar Gate
#         uses: alejandra-jamilis/sonar-build-breaker-action@master
#         id: check
#         with:
#           sonarqube_url: https://desa-sonar.bluex.cl
#           sonarqube_token: 484c233f4eba6e6adc38bf2c0b7cfa207614c2e0
#           task_id: AXa5OngSVuj3vjvymVTU
